# client netlify.toml

# [build]
#   command = "yarn build"
#   functions = "functions"
#   publish = "public"

# [build.environment]
#   APP_SPECIFIC_FLAG = "true"

# make sure "fetchVariable.js" file is correct as well
[[redirects]]
  from = "api/*"
  to = "https://focus-interval.fly.dev/:splat"
  status = 200

# [[redirects]]
#   from = "https://focus-interval.netlify.app/*"
#   to = "https://focus-interval.netlify.app/"
#   status = 200

[[redirects]]
  from = "/*"
  to = "/"
  status = 301
